In [1]:
import numpy as np

In [2]:
from numpy import random

In [5]:
#100  tk limit set hu gyi limit kitni bhi de skte hai
x=random.randint(100)

In [6]:
x

84

In [14]:
x=random.randint(10)
if(x==5 or x==9):
    print("you win the lottery",x)
else:
    print("you lost",x)

you win the lottery 9


In [15]:
# o-1 ke bitch float values lena hai tu
y=random.rand()
y

0.5440392730643668

In [16]:
z=random.randint(100,size=5)
z

array([36, 23, 80, 78, 60])

In [19]:
#teen dalenge ti 3d ban jayega or 2 dalenge tu 2d bn jayaega
z1=random.randint(100,size=(3,3,3))
z1

array([[[40, 85, 12],
        [15,  1, 15],
        [ 1, 34, 62]],

       [[39, 88, 68],
        [91, 75, 99],
        [41, 38, 30]],

       [[84, 39, 40],
        [43, 59, 45],
        [ 0, 26, 53]]])

In [20]:
z2=random.choice([5,6,7,8,20])
z2

20

In [21]:
z2=random.choice([5,6,7,8,20],size=5)
z2

array([ 6,  8,  8, 20,  8])