In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
for i,j in np.ndenumerate(a):
    print(i,j)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9


In [6]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
for i,j in np.ndenumerate(b):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [8]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,3,4]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 3, 4]]])

In [9]:
for i,j in np.ndenumerate(c):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 0
(1, 1, 1) 3
(1, 1, 2) 4


In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [16]:
a=np.array([[1,2,3],[4,5,6],[3,6,4],[7,8,6]])
b=np.array([[3,4,5],[7,8,9],[9,7,5],[5,9,3]])
c=np.concatenate((a,b),axis=1)
c

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8, 9],
       [3, 6, 4, 9, 7, 5],
       [7, 8, 6, 5, 9, 3]])

In [17]:
#for joining against row
e=np.hstack((a,b))
e

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8, 9],
       [3, 6, 4, 9, 7, 5],
       [7, 8, 6, 5, 9, 3]])

In [18]:
#for joining against column
f=np.vstack((a,b))
f

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 4],
       [7, 8, 6],
       [3, 4, 5],
       [7, 8, 9],
       [9, 7, 5],
       [5, 9, 3]])

In [19]:
#for join against depth
g=np.dstack((a,b))
g

array([[[1, 3],
        [2, 4],
        [3, 5]],

       [[4, 7],
        [5, 8],
        [6, 9]],

       [[3, 9],
        [6, 7],
        [4, 5]],

       [[7, 5],
        [8, 9],
        [6, 3]]])

In [20]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.stack((x,y))
z

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
z1=np.hstack((x,y))
z1

array([1, 2, 3, 4, 5, 6])

In [22]:
z2=np.vstack((x,y))
z2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
z3=np.dstack((x,y))
z3

array([[[1, 4],
        [2, 5],
        [3, 6]]])